apps/course/urls.py
from django.conf.urls import url,include
from course.views import CourseList,CourseDetailView

urlpatterns = [
    # 课程信息
    url(r'list/$', CourseList.as_view(), name='list'),

    # 课程详情
    url(r'details/(?P<course_id>.*)$', CourseDetailView.as_view(), name='details'),


]

apps/user/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from user.views import IndexView, LoginView, LogoutView,RegisterView,ActiveUserView,ForgetPwdView,\
    ResetView,ModifyPwdView,UserInfoView,ChangePwdView,UserCourseView,UserOrderView,UserWorkView,\
    UploadImageView

urlpatterns = [
    # 主页
    url(r'^index/$', IndexView.as_view(),name='index'),
    # 登录页面
    url(r'^login/$', LoginView.as_view(),name='login'),
    # 退出登录
    url(r'^logout/$', LogoutView.as_view(),name='logout'),
    # 注册页面
    url(r'^register/$', RegisterView.as_view(),name='register'),
    # 激活邮箱
    url(r'^active/(?P<active_code>.*)/$', ActiveUserView.as_view(),name='register'),


    # 忘记密码
    url(r'^forget_pwd/$', ForgetPwdView.as_view(), name='forget_pwd'),

    # 修改密码get
    url(r'^reset/(?P<reset_code>.*)/$', ResetView.as_view(), name='reset_pwd'),

    # 修改密码post
    url(r'^modify_pwd/$', ModifyPwdView.as_view(), name="modify_pwd"),


    # 用户

    # 用户信息
    url(r'info/$', UserInfoView.as_view(), name='info'),

    # 修改密码
    url(r'change_pwd/$', ChangePwdView.as_view(), name='change_pwd'),

    # 用户课程表
    url(r'course/$', UserCourseView.as_view(), name='course'),

    # 用户订单
    url(r'order/$', UserOrderView.as_view(), name='order'),

    # 用户作业
    url(r'homework/$', UserWorkView.as_view(), name="homework"),

    # 用户头像上传
    url(r'^image/upload/$', UploadImageView.as_view(), name="image_upload"),






]

tanzhoupro/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from user.views import IndexView

from tanzhoupro.settings import MEDIA_ROOT
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # 关于用户user
    url(r'^users/', include('user.urls',namespace='user')),

    # 关于课程course
    url(r'^courses/', include('course.urls',namespace='course')),

    # 获取验证码
    url(r'^captcha/', include('captcha.urls')),

    #配置上传文件的访问处理函数
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
]

apps/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime
# Create your models here.

class UserInfo(AbstractUser):
    nick_name = models.CharField(max_length=50, verbose_name=u'昵称')
    birthday = models.DateField(verbose_name=u'生日', null=True, blank=True)
    gender = models.CharField(max_length=10,choices=(('male',u'男'),('female',u'女')),default='female')
    image = models.ImageField(upload_to='image/%Y/%m',default=u'',max_length=100)
    phone = models.IntegerField(verbose_name=u'手机号码', null=True,blank=True)
    qq = models.IntegerField(null=True,blank=True)

    class Meta:
        verbose_name = u'用户信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.username


class Banner(models.Model):
    name = models.CharField(max_length=30, verbose_name=u"轮播图名")
    image = models.ImageField(upload_to='banner/%Y/%m', default=u"", max_length=100)
    url = models.URLField(max_length=100, verbose_name=u"访问地址")
    index = models.IntegerField(default=0, verbose_name=u"顺序")
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

    class Meta:
        verbose_name = u"轮播图"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class EmailVerify(models.Model):
    code = models.CharField(max_length=20, verbose_name=u"验证码")
    email = models.EmailField(max_length=25, verbose_name=u"邮箱")
    send_type = models.CharField(max_length=10, choices=(('register', '注册'), ('reset', '找回密码')), verbose_name=u"类型")
    send_time = models.DateTimeField(default=datetime.now, verbose_name=u"发送时间")

    class Meta:
        verbose_name = u"验证"
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{0}({1})'.format(self.code, self.email)

apps/user/forms.py
# -*- coding: utf-8 -*-
from django import forms
from captcha.fields import CaptchaField
from user.models import UserInfo

class LoginForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True,min_length=6)

class RegisterForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True,min_length=6)
    captcha = CaptchaField(error_messages={'invalid' : u'验证码错误!'})

# 忘记密码
class ForgetPwdForm(forms.Form):
    email = forms.EmailField(required=True)
    captcha = CaptchaField(error_messages={'invalid' : u'验证码错误!'})

# 邮箱修改密码的验证字段
class ModifyPwdForm(forms.Form):
    email = forms.EmailField(required=True)
    password1 = forms.CharField(required=True, min_length=6)
    password2 = forms.CharField(required=True, min_length=6)


# 在个人信息中修改密码的验证字段
class ChangePwdForm(forms.Form):
    email = forms.EmailField(required=True)
    passwordold = forms.CharField(required=True, min_length=6)
    password1 = forms.CharField(required=True, min_length=6)
    password2 = forms.CharField(required=True, min_length=6)


# 上传图片
class UploadImageForm(forms.ModelForm):
    class Meta:
        model = UserInfo  # 说明要引用的model是哪个表
        fields = ['image']  # 说明要使用的字段有那个


# 用户信息修改
class UploadInfoForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = ['nick_name', 'gender', 'email', 'phone', 'qq']

templates/my_course.html
{% extends 'my_base.html' %}
{% load staticfiles %}


{% block content %}
    <div class="_3e23-">
        <ul>
            <li class="hWd71"><a href="{% url 'user:course' %}">我的课程表</a></li>
            <li class=""><a href="{% url 'user:order' %}">我的订单</a></li>
            <li class=""><a href="{% url 'user:homework' %}">我的作业</a></li>
            <li class=""><a href="{% url 'user:info' %}">个人资料</a></li>
        </ul>
    </div>
    <div class="content"><h1 class="contentTitle">我的课程表</h1>
        <div class="contentBody">
            <div class="_24mIm"><a href="javascript:;">全部课程</a>
                <ul>
                    <li class=""><a href="javascript:;">公开课</a></li>
                    <li class="_10fSl"><a href="javascript:;">VIP课</a></li>
                    <li class=""><a href="javascript:;">正在直播</a></li>
                </ul>
            </div>
            <div class="_2pbWq">
                <div class="_1Ac_A">
                    <div class="TE0cD">
                        <div class="_2QHbj"><a href="https://www.shiguangkey.com/course/1950" target="_blank"
                                               class="_2OIyH">
                            <img src="{% static '/img/file/201804/07/20180328160434134005047.png' %}" alt="封面"><span
                                class="_2E_Tb S02jn">VIP</span></a>
                            <div class="_2b4RL"><a href="https://www.shiguangkey.com/course/1950"
                                                   target="_blank" class="_1Ngl7">潭州人工智能VIP第一期预科班</a>
                                <div>
                                    <div class="_37vIc"><!-- react-text: 2585 -->开课时间：<!-- /react-text --><b>2018-04-08
                                        20:30</b></div>
                                    <div class="_37vIc"><!-- react-text: 2588 -->所在班期：
                                        <!-- /react-text --><b>1期</b></div>
                                </div>
                                <div class="dHKOd">
                                    <div class="_3FRy4" href="javascript:;"><!-- react-text: 2592 -->联系老师
                                        <!-- /react-text -->
                                        <ul>
                                            <div class="_1Ac_A">
                                                <div class="TE0cD">
                                                    <li><a href="javascript:;" class="_1ocyD">暂无联系方式</a></li>
                                                </div>
                                            </div>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="_3fRfU"><span class="OsYjr"><span class="_3WJlz"></span></span><span><!-- react-text: 2602 -->开课提醒已
                                <!-- /react-text --><!-- react-text: 2603 -->关闭<!-- /react-text --></span></div>
                            <button class="_1Ncey">进入教室</button>
                        </div>
                        <div class="_2QHbj"><a href="https://www.shiguangkey.com/course/1832" target="_blank"
                                               class="_2OIyH"><img
                                src="{% static '/img/file/201804/07/20180308161251858507349.png' %}" alt="封面"><span
                                class="_2E_Tb S02jn">VIP</span></a>
                            <div class="_2b4RL"><a href="https://www.shiguangkey.com/course/1832"
                                                   target="_blank" class="_1Ngl7">python 设计模式</a>
                                <div><!-- react-text: 2612 --><!-- /react-text -->
                                    <div class="_37vIc"><!-- react-text: 2614 -->所在班期：
                                        <!-- /react-text --><b>已过期</b></div>
                                </div>
                                <div class="dHKOd">
                                    <div class="_3FRy4" href="javascript:;"><!-- react-text: 2618 -->联系老师
                                        <!-- /react-text -->
                                        <ul>
                                            <div class="_1Ac_A">
                                                <div class="TE0cD">
                                                    <li><a href="javascript:;" class="_1ocyD">暂无联系方式</a></li>
                                                </div>
                                            </div>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="_3fRfU"><span class="OsYjr"><span class="_3WJlz"></span></span><span><!-- react-text: 2628 -->开课提醒已
                                <!-- /react-text --><!-- react-text: 2629 -->关闭<!-- /react-text --></span></div>
                            <button>已过期</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/my_homework.html
{% extends 'my_base.html' %}
{% load staticfiles %}

{% block content %}
    <div class="_3e23-">
        <ul>
            <li class=""><a href="{% url 'user:course' %}">我的课程表</a></li>
            <li class=""><a href="{% url 'user:order' %}">我的订单</a></li>
            <li class="hWd71"><a href="{% url 'user:homework' %}">我的作业</a></li>
            <li class=""><a href="{% url 'user:info' %}">个人资料</a></li>
        </ul>
    </div>
    <div class="content"><h1 class="contentTitle">我的作业</h1>
        <div class="contentBody">
            <div class="i73oz"><input type="text" class="_1QdU3" placeholder="输入要查询的作业名称"><a href="javascript:;"
                                                                                             class="_2u3d0">查询</a><a
                    href="javascript:;" class="_1z3qa">重置</a></div>
            <div class="_3iUAz">
                <div class="TZ-Tab TZ-Tab-top">
                    <div role="tablist" class="TZ-Tab-bar" tabindex="0">
                        <div class="TZ-Tab-nav-container"><span unselectable="unselectable"
                                                                class="TZ-Tab-tab-prev TZ-Tab-tab-btn-disabled"><span
                                class="TZ-Tab-tab-prev-icon"></span></span><span unselectable="unselectable"
                                                                                 class="TZ-Tab-tab-next TZ-Tab-tab-btn-disabled"><span
                                class="TZ-Tab-tab-next-icon"></span></span>
                            <div class="TZ-Tab-nav-wrap">
                                <div class="TZ-Tab-nav-scroll">
                                    <div class="TZ-Tab-nav TZ-Tab-nav-animated">
                                        <div class="TZ-Tab-ink-bar TZ-Tab-ink-bar-animated"
                                             style="display: block; transform: translate3d(0px, 0px, 0px); width: 82px;"></div>
                                        <div role="tab" aria-disabled="false" aria-selected="true"
                                             class="TZ-Tab-tab-active TZ-Tab-tab">待完成
                                        </div>
                                        <div role="tab" aria-disabled="false" aria-selected="false"
                                             class=" TZ-Tab-tab">已完成
                                        </div>
                                        <div role="tab" aria-disabled="false" aria-selected="false"
                                             class=" TZ-Tab-tab">全部
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="TZ-Tab-content TZ-Tab-content-animated"
                         style="transform: translateX(0%) translateZ(0px);">
                        <div role="tabpanel" aria-hidden="false" class="TZ-Tab-tabpane TZ-Tab-tabpane-active">
                            <div>
                                <div class="_1Ac_A">
                                    <div class="TE0cD">
                                        <div class="_2Ng_r"><img src="../static/img/file/201804/07/NoNo.32f2bd65.jpg"
                                                                 alt="暂时没有作业记录哦">
                                            <h2>暂时没有作业记录哦</h2></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div role="tabpanel" aria-hidden="true" class="TZ-Tab-tabpane TZ-Tab-tabpane-inactive">
                            <div>
                                <div class="_1Ac_A">
                                    <div class="TE0cD">
                                        <div class="_2Ng_r"><img src="../static/img/file/201804/07/NoNo.32f2bd65.jpg"
                                                                 alt="暂时没有作业记录哦">
                                            <h2>暂时没有作业记录哦</h2></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div role="tabpanel" aria-hidden="true" class="TZ-Tab-tabpane TZ-Tab-tabpane-inactive">
                            <div>
                                <div class="_1Ac_A">
                                    <div class="TE0cD">
                                        <div class="_2Ng_r"><img src="../static/img/file/201804/07/NoNo.32f2bd65.jpg"
                                                                 alt="暂时没有作业记录哦">
                                            <h2>暂时没有作业记录哦</h2></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/my_info.html
{% extends 'my_base.html' %}
{% load staticfiles %}

{% block custom_css %}

{% endblock %}


{% block content %}

    <div class="_3e23-">
        <ul>
            <li class=""><a href="{% url 'user:course' %}">我的课程表</a></li>
            <li class=""><a href="{% url 'user:order' %}">我的订单</a></li>
            <li class=""><a href="{% url 'user:homework' %}">我的作业</a></li>
            <li class="hWd71"><a href="{% url 'user:info' %}">个人资料</a></li>
        </ul>
    </div>
    <div class="content"><h1 class="contentTitle">个人资料</h1>
        <div class="contentBody">
            <div class="B6J2b">
                <div class="TZ-Tab TZ-Tab-top">
                    <div role="tablist" class="TZ-Tab-bar" tabindex="0">
                        <div class="TZ-Tab-nav-container"><span unselectable="unselectable"
                                                                class="TZ-Tab-tab-prev TZ-Tab-tab-btn-disabled"><span
                                class="TZ-Tab-tab-prev-icon"></span></span><span unselectable="unselectable"
                                                                                 class="TZ-Tab-tab-next TZ-Tab-tab-btn-disabled"><span
                                class="TZ-Tab-tab-next-icon"></span></span>
                            <div class="TZ-Tab-nav-wrap">
                                <div class="TZ-Tab-nav-scroll">
                                    <div class="TZ-Tab-nav TZ-Tab-nav-animated">
                                        <div class="TZ-Tab-ink-bar TZ-Tab-ink-bar-animated"
                                             style="display: block; transform: translate3d(0px, 0px, 0px); width: 96px;"></div>
                                        <div role="tab" aria-disabled="false" aria-selected="true"
                                             class="TZ-Tab-tab-active TZ-Tab-tab"><a href="{% url 'user:info' %}">个人信息</a>
                                        </div>
                                        <div role="tab" aria-disabled="false" aria-selected="false"
                                             class=" TZ-Tab-tab"><a href="{% url 'user:change_pwd' %}">修改密码</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="TZ-Tab-content TZ-Tab-content-animated"
                         style="transform: translateX(0%) translateZ(0px);">
                        <div role="tabpanel" aria-hidden="false" class="TZ-Tab-tabpane TZ-Tab-tabpane-active">
                            <div>
                                <table cellspacing="15px" cellpadding="" class="_3liV0">

                                    <form class="clearfix" id="jsAvatarForm" enctype="multipart/form-data"
                                          autocomplete="off" method="post" action="{% url 'user:image_upload' %}"
                                          target='frameFile'>

                                        <label class="changearea" for="avatarUp">
                                            <span id="avatardiv" class="pic">
                                                <img width="100" height="100" class="js-img-show" id="avatarShow"
                                                     src="{{ MEDIA_URL }}{{ request.user.image }}"/>
                                            </span>
                                            <span class="fl upload-inp-box" style="margin-left:70px;">
                                                <span class="button btn-green btn-w100" id="jsAvatarBtn">修改头像</span>

                                                <input type="file" name="image" id="avatarUp" class="js-img-up"/>

                                            </span>
                                        </label>

                                        <input class="_2qCjw" id="jsLoginBtn" type="submit" value="确定"/>
                                        {% csrf_token %}
                                    </form>

                                </table>

                                <hr>

                                <form action="{% url 'user:info' %}" method="post">
                                    <table cellspacing="15px" cellpadding="" class="_3liV0">
                                        <tbody>
                                        <tr>
                                            <td>账号：</td>

                                            <td>{{ request.user.username }}
                                                <a href="{% url 'user:change_pwd' %}" class="_3RrAT">修改密码</a>
                                            </td>

                                        </tr>
                                        <tr>
                                            <td><span>昵称：</span><i>*</i></td>
                                            <td><input type="text" class="_1zVvg" name="nick_name"
                                                       placeholder="昵称长度2-15个字，可以是汉字、字母或数字"
                                                       value="{{ request.user.nick_name }}">
                                                <p class="_1Qh6M"></p></td>
                                        </tr>
                                        <tr>

                                            <td>性别：</td>
                                            <td><label class="_10Fbo"><input type="radio" value="male" name="gender"
                                                    {% if request.user.gender == 'male' %}  checked="checked" {% endif %}>
                                                男</label>
                                                <label
                                                        class="_10Fbo"><input type="radio" value="female" name="gender"
                                                        {% if request.user.gender == 'female' %} checked="checked" {% endif %}>
                                                    女</label></td>
                                        </tr>
                                        <tr>
                                            <td>常用邮箱：</td>
                                            <td><input type="text" class="_7oaxl" placeholder="name@example.com"
                                                       name="email" readonly="readonly"
                                                       value="{{ request.user.email }}"><a href="javascript:;"
                                                                                           class="iZB-C">验证邮箱</a><br>
                                                <p class="_1Qh6M">用于优质课程的学习提醒等服务，邮箱不会对外公开，请放心</p></td>
                                        </tr>
                                        <tr>
                                            <td>手机号码：</td>
                                            <td><input type="text" class="_7oaxl" placeholder="请输入手机号码" name="phone"

                                                       value="{{ request.user.phone }}">
                                                <div id="jsChangePhoneDialog" class="_1DnDc">验证手机</div>
                                                <br>
                                                <p class="_1Qh6M">用于优质课程的学习提醒等服务，手机号不会对外公开，请放心</p></td>
                                        </tr>
                                        <tr>
                                            <td><span>绑定QQ：</span><i>*</i></td>
                                            <td><input type="text" class="_7oaxl" placeholder="请输入常用的QQ号码" name="qq"
                                                       value="{{ request.user.qq | default_if_none:'' }}">
                                                <p class="_1Qh6M"></p></td>
                                        </tr>
                                        <tr>
                                            <td>生日：</td>
                                            <td><input placeholder="选择日期" class="_24gyZ" readonly="readonly"
                                                       name="birthday"
                                                       value="{{ request.user.birthday | default_if_none:'' }}"></td>
                                        </tr>
                                        <tr>
                                            <td>简介：</td>
                                            <td><textarea maxlength="150" class="_2Q8lf" name="summary"
                                                          placeholder="请填写简介，15~150个字之间"></textarea></td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <input class="_2qCjw" id="" type="submit" value="确定"/>
                                            </td>

                                        </tr>
                                        </tbody>
                                    </table>
                                    {% csrf_token %}
                                </form>

                            </div>

                        </div>
                        <div role="tabpanel" aria-hidden="true"
                             class="TZ-Tab-tabpane TZ-Tab-tabpane-inactive"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block custom_js %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
{% endblock %}

templates/my_paasword.html
{% extends 'my_base.html' %}
{% load staticfiles %}

{% block content %}
    <div class="_3e23-">
        <ul>
            <li class=""><a href="{% url 'user:course' %}">我的课程表</a></li>
            <li class=""><a href="{% url 'user:order' %}">我的订单</a></li>
            <li class=""><a href="{% url 'user:homework' %}">我的作业</a></li>
            <li class="hWd71"><a href="{% url 'user:info' %}">个人资料</a></li>
        </ul>
    </div>
    <div class="content"><h1 class="contentTitle">个人资料</h1>
        <div class="contentBody">
            <div class="B6J2b">
                <div class="TZ-Tab TZ-Tab-top">
                    <div role="tablist" class="TZ-Tab-bar" tabindex="0">
                        <div class="TZ-Tab-nav-container">

                            <span unselectable="unselectable" class="TZ-Tab-tab-prev TZ-Tab-tab-btn-disabled">
                                <span class="TZ-Tab-tab-prev-icon"></span>
                            </span>

                            <span unselectable="unselectable" class="TZ-Tab-tab-next TZ-Tab-tab-btn-disabled">
                                <span class="TZ-Tab-tab-next-icon"></span>
                            </span>

                            <div class="TZ-Tab-nav-wrap">
                                <div class="TZ-Tab-nav-scroll">
                                    <div class="TZ-Tab-nav TZ-Tab-nav-animated">
                                        <div class="TZ-Tab-ink-bar TZ-Tab-ink-bar-animated"
                                             style="display: block; transform: translate3d(0px, 0px, 0px); width: 96px; height: 0px"></div>
                                        <div role="tab" aria-disabled="false" aria-selected="false"
                                             class=" TZ-Tab-tab"><a href="{% url 'user:info' %}">个人信息</a>
                                        </div>
                                        <div role="tab" aria-disabled="false" aria-selected="true"
                                             class="TZ-Tab-tab-active TZ-Tab-tab"><a href="{% url 'user:change_pwd' %}">修改密码</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="TZ-Tab-content TZ-Tab-content-animated"
                         style="transform: translateX(0%) translateZ(0px);">
                        <div role="tabpanel" aria-hidden="false" class="TZ-Tab-tabpane TZ-Tab-tabpane-active">
                            <div role="tabpanel" aria-hidden="false"
                                 class="TZ-Tab-tabpane TZ-Tab-tabpane-active">
                                <div>

                                    <form action="{% url 'user:change_pwd' %}" method="post">
                                        {{ change_form.errors }}
                                        <table cellspacing="15" cellpadding="" class="_3liV0 errorput">
                                            <tbody>
                                            <tr>
                                                <td>旧密码：</td>
                                                <td><input type="password" class="_1oud1" name="passwordold"
                                                           placeholder="请输入旧密码"
                                                           value="">
                                                    <p class="_1Qh6M"></p><a
                                                            href="{% url 'user:forget_pwd' %}"
                                                            class="_3wKVP">忘记密码？</a></td>
                                            </tr>
                                            <tr>
                                                <td>新密码：</td>
                                                <td><input type="password" class="_1oud1" name="password1"
                                                           placeholder="请输入新密码"
                                                           value="">
                                                    <p class="_1Qh6M"></p></td>
                                            </tr>
                                            </tbody>

                                            <input type="hidden" name="email" value="{{ email }}">

                                            <tr>
                                                <td>确认密码：</td>
                                                <td><input type="password" class="_1oud1" name="password2"
                                                           placeholder="请确认新密码"
                                                           value="">
                                                    <p class="_1Qh6M"></p></td>
                                            </tr>
                                            <tr>
                                                <td>{% for key, error in change_form.errors.items %}{{ error }}{% endfor %}{{ msg }}</td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                                <td>

                                                    <input type="submit" class="_1-xUc" value="提交">
                                                </td>
                                            </tr>

                                        </table>

                                        {% csrf_token %}
                                    </form>

                                </div>
                            </div>


                        </div>
                        <div role="tabpanel" aria-hidden="true"
                             class="TZ-Tab-tabpane TZ-Tab-tabpane-inactive"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block custom_js %}
    <script type="text/javascript" src="{% static 'css/user/index.css' %}"></script>
{% endblock %}